### ISSUE TITLE
Create base exception to cleanly report plugin exceptions from the compiler

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta#1205]
# Goal

This exception should allow plugin developers to report detailed error messages to end-users. 
In a later stage, these specific exceptions will be picked up for automated handling.

# Tasks
- [ ] Add an appropriately named Exception to the plugins package for the plugin developers to cleanly report errors to end-users. It should have a message.
- [ ] Document how to use it
- [ ] Create an associated subtype of ExternalException to wrap these exceptions and produce proper output.

**Comment by sanderr** [comment]
Could you elaborate on what should differentiate this associated subtype of ExternalException from its parent? Currently any Exception raised from a plugin is wrapped in an ExternalException (except for [this](https://github.com/inmanta/inmanta/blob/ed3d16093a8d46a74a8c7cb67aeb87ac39dbb050/src/inmanta/ast/statements/call.py#L199-L200) one but I assume that's a mistake, I'll fix that in this pull request as well). Is the goal just to differentiate at type level whether we're dealing with an explicitly raised, plugin developer declared exception or not? Or should the ExternalException child actually override behavior?

**Comment by wouterdb** [comment]
1. That seems like a bug indeed
2. It would be to differentiate at the type level indeed
3. For now, now overrides required I think, if all formatting is OK.
