### ISSUE TITLE
Create standalone support collection command

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1374]
For providing support and bug reporting a command should exist that collects information about the current deployment. Possibly the tool has options to disable certain data:

- [ ] Collect the full server configuration
- [x] Include a database dump
- [x] Include all logs
- [x] Include all loaded extensions, slice and their versions
- [x] Report database statistics
- [x] Report OS data such as: disk allocation, memory usage, cpu, ...
- [x] Include usage data metrics (also from get_status)
