### ISSUE TITLE
Support python 3.8

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta#2221]
We should add support for py3.8

- [ ] add py38 to tox.ini
- [ ] fix all tests to run on py38 
- [ ] add py3.8 to pytestdocker
