### ISSUE TITLE
Export command should give non-zero exit code on failure

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta#2487]
**Problem:**

When no environment id is given, the export command fails with the following log lines:

```
stdout: inmanta.export           WARNING Empty deployment model.
inmanta.export           ERROR   The environment for this model should be set!
inmanta.export           INFO    Committed resources with version 0
```

However, the exit code is zero, which indicates success.

**Tasks:**

- [ ] Investigate the impact of returning a non-zero exit code in case of failure (server-side compile, lsm, etc.)
- [ ] Ensure that a non-zero exit code is returned when the environment id is not set.
- [ ] Document exit codes 
- [ ] Ensure lsm still works
