### ISSUE TITLE
Test new version pytest-postgresql

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta#2494]
**Description:**

The version of the `pytest-postgresql` dependency is currently pinned to 2.5.0, because version 2.5.1 didn't work on Centos7 (See: https://github.com/ClearcodeHQ/pytest-postgresql/issues/338). As such `docker-pytest` failed for Centos7. This issue should be solved in version 2.5.2.

**Tasks:**

- [x] Verify that the issue is resolved in version 2.5.2
- [x] Bump the `pytest-postgresql` version on core
- [x] Ensure that dependabot doesn't ignore `pytest-postgresql` anymore by removing it from the ignore section in  `.github/dependabot.yml`

**Comment by edvgui** [comment]
Changelog of 2.5.2 says it dealt with systems without C locale: https://github.com/ClearcodeHQ/pytest-postgresql/blob/master/CHANGES.rst#252

Currently running tests
